version: "3"
services:
  queue:
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
  tweets:
    build: "./tweets"
    ports:
      - "4000:4000"
    environment:
      - DISABLE_SECURITY=true
  profile:
    build: "./profile"
    ports:
      - "4001:4001"
    environment:
      - DISABLE_SECURITY=true
  trending:
    build: "./trending"
    ports:
      - "4002:4002"
    environment:
      - DISABLE_SECURITY=true
  auth:
    build: ./auth
    ports:
      - "4003:4003"
